export const ADMIN_USERS_ALL_REQUEST = 'ADMIN_USERS_ALL_REQUEST'
export const ADMIN_USERS_ALL_SUCCESS = 'ADMIN_USERS_ALL_SUCCESS'
export const ADMIN_USERS_ALL_FAIL = 'ADMIN_USERS_ALL_FAIL'
export const ADMIN_USERS_ALL_RESET = 'ADMIN_USERS_ALL_RESET'

export const ADMIN_USER_REQUEST = 'ADMIN_USER_REQUEST'
export const ADMIN_USER_SUCCESS = 'ADMIN_USER_SUCCESS'
export const ADMIN_USER_FAIL = 'ADMIN_USER_FAIL'
export const ADMIN_USER_RESET = 'ADMIN_USER_RESET'

export const ADMIN_USER_DELETE_REQUEST = 'ADMIN_USER_DELETE_REQUEST'
export const ADMIN_USER_DELETE_SUCCESS = 'ADMIN_USER_DELETE_SUCCESS'
export const ADMIN_USER_DELETE_FAIL = 'ADMIN_USER_DELETE_FAIL'
export const ADMIN_USER_DELETE_RESET = 'ADMIN_USER_DELETE_RESET'

export const ADMIN_USER_UPDATE_REQUEST = 'ADMIN_USER_UPDATE_REQUEST'
export const ADMIN_USER_UPDATE_SUCCESS = 'ADMIN_USER_UPDATE_SUCCESS'
export const ADMIN_USER_UPDATE_FAIL = 'ADMIN_USER_UPDATE_FAIL'
export const ADMIN_USER_UPDATE_RESET = 'ADMIN_USER_UPDATE_RESET'

