export const CONVO_START_REQUEST = 'CONVO_START_REQUEST'
export const CONVO_START_SUCCESS = 'CONVO_START_SUCCESS'
export const CONVO_START_FAIL = 'CONVO_START_FAIL'
export const CONVO_START_RESET = 'CONVO_START_RESET'

export const CONVO_NEW_MESSAGE_REQUEST = 'CONVO_NEW_MESSAGE_REQUEST'
export const CONVO_NEW_MESSAGE_SUCCESS = 'CONVO_NEW_MESSAGE_SUCCESS'
export const CONVO_NEW_MESSAGE_FAIL = 'CONVO_NEW_MESSAGE_FAIL'
export const CONVO_NEW_MESSAGE_RESET = 'CONVO_NEW_MESSAGE_RESET'

export const CONVO_GET_CONVO_REQUEST = 'CONVO_GET_CONVO_REQUEST'
export const CONVO_GET_CONVO_SUCCESS = 'CONVO_GET_CONVO_SUCCESS'
export const CONVO_GET_CONVO_FAIL = 'CONVO_GET_CONVO_FAIL'

export const CONVO_EXIST_CONVO_REQUEST = 'CONVO_EXIST_CONVO_REQUEST'
export const CONVO_EXIST_CONVO_SUCCESS = 'CONVO_EXIST_CONVO_SUCCESS'
export const CONVO_EXIST_CONVO_FAIL = 'CONVO_EXIST_CONVO_FAIL'
export const CONVO_EXIST_CONVO_RESET = 'CONVO_EXIST_CONVO_RESET'

export const CONVO_USER_CONVOS_REQUEST = 'CONVO_USER_CONVOS_REQUEST'
export const CONVO_USER_CONVOS_SUCCESS = 'CONVO_USER_CONVOS_SUCCESS'
export const CONVO_USER_CONVOS_FAIL = 'CONVO_USER_CONVOS_FAIL'
export const CONVO_USER_CONVOS_RESET = 'CONVO_USER_CONVOS_RESET'