export const INTERNSHIP_CREATE_REQUEST = 'INTERNSHIP_CREATE_REQUEST'
export const INTERNSHIP_CREATE_SUCCESS = 'INTERNSHIP_CREATE_SUCCESS'
export const INTERNSHIP_CREATE_FAIL = 'INTERNSHIP_CREATE_FAIL'
export const INTERNSHIP_CREATE_RESET = 'INTERNSHIP_CREATE_RESET'

export const INTERNSHIP_PUBLIC_REQUEST = 'INTERNSHIP_PUBLIC_REQUEST'
export const INTERNSHIP_PUBLIC_SUCCESS = 'INTERNSHIP_PUBLIC_SUCCESS'
export const INTERNSHIP_PUBLIC_FAIL = 'INTERNSHIP_PUBLIC_FAIL'
export const INTERNSHIP_PUBLIC_RESET = 'INTERNSHIP_PUBLIC_RESET'

export const INTERNSHIP_GET_ALL_REQUEST = 'INTERNSHIP_GET_ALL_REQUEST'
export const INTERNSHIP_GET_ALL_SUCCESS = 'INTERNSHIP_GET_ALL_SUCCESS'
export const INTERNSHIP_GET_ALL_FAIL = 'INTERNSHIP_GET_ALL_FAIL'

export const INTERNSHIP_ALL_REQUEST = 'INTERNSHIP_ALL_REQUEST'
export const INTERNSHIP_ALL_SUCCESS = 'INTERNSHIP_ALL_SUCCESS'
export const INTERNSHIP_ALL_FAIL = 'INTERNSHIP_ALL_FAIL'
export const INTERNSHIP_ALL_RESET = 'INTERNSHIP_ALL_RESET'

export const INTERNSHIP_DELETE_REQUEST = 'INTERNSHIP_DELETE_REQUEST'
export const INTERNSHIP_DELETE_SUCCESS = 'INTERNSHIP_DELETE_SUCCESS'
export const INTERNSHIP_DELETE_FAIL = 'INTERNSHIP_DELETE_FAIL'
export const INTERNSHIP_DELETE_RESET = 'INTERNSHIP_DELETE_RESET'

export const INTERNSHIP_GET_REQUEST = 'INTERNSHIP_GET_REQUEST'
export const INTERNSHIP_GET_SUCCESS = 'INTERNSHIP_GET_SUCCESS'
export const INTERNSHIP_GET_FAIL = 'INTERNSHIP_GET_FAIL'
export const INTERNSHIP_GET_RESET = 'INTERNSHIP_GET_RESET'

export const INTERNSHIP_ADD_STUDENT_REQUEST = 'INTERNSHIP_ADD_STUDENT_REQUEST'
export const INTERNSHIP_ADD_STUDENT_SUCCESS = 'INTERNSHIP_ADD_STUDENT_SUCCESS'
export const INTERNSHIP_ADD_STUDENT_FAIL = 'INTERNSHIP_ADD_STUDENT_FAIL'
export const INTERNSHIP_ADD_STUDENT_RESET = 'INTERNSHIP_ADD_STUDENT_RESET'

export const INTERNSHIP_ACCEPT_STUDENT_REQUEST = 'INTERNSHIP_ACCEPT_STUDENT_REQUEST'
export const INTERNSHIP_ACCEPT_STUDENT_SUCCESS = 'INTERNSHIP_ACCEPT_STUDENT_SUCCESS'
export const INTERNSHIP_ACCEPT_STUDENT_FAIL = 'INTERNSHIP_ACCEPT_STUDENT_FAIL'
export const INTERNSHIP_ACCEPT_STUDENT_RESET = 'INTERNSHIP_ACCEPT_STUDENT_RESET'

export const INTERNSHIP_ACCEPT_DELETE_STUDENT_REQUEST = 'INTERNSHIP_ACCEPT_DELETE_STUDENT_REQUEST'
export const INTERNSHIP_ACCEPT_DELETE_STUDENT_SUCCESS = 'INTERNSHIP_ACCEPT_DELETE_STUDENT_SUCCESS'
export const INTERNSHIP_ACCEPT_DELETE_STUDENT_FAIL = 'INTERNSHIP_ACCEPT_DELETE_STUDENT_FAIL'
export const INTERNSHIP_ACCEPT_DELETE_STUDENT_RESET = 'INTERNSHIP_ACCEPT_DELETE_STUDENT_RESET'