export const OFFER_CREATE_REQUEST = 'OFFER_CREATE_REQUEST'
export const OFFER_CREATE_SUCCESS = 'OFFER_CREATE_SUCCESS'
export const OFFER_CREATE_FAIL = 'OFFER_CREATE_FAIL'
export const OFFER_CREATE_RESET = 'OFFER_CREATE_RESET'

export const OFFER_PUBLIC_REQUEST = 'OFFER_PUBLIC_REQUEST'
export const OFFER_PUBLIC_SUCCESS = 'OFFER_PUBLIC_SUCCESS'
export const OFFER_PUBLIC_FAIL = 'OFFER_PUBLIC_FAIL'
export const OFFER_PUBLIC_RESET = 'OFFER_PUBLIC_RESET'

export const OFFER_GET_ALL_REQUEST = 'OFFER_GET_ALL_REQUEST'
export const OFFER_GET_ALL_SUCCESS = 'OFFER_GET_ALL_SUCCESS'
export const OFFER_GET_ALL_FAIL = 'OFFER_GET_ALL_FAIL'

export const OFFER_ALL_REQUEST = 'OFFER_ALL_REQUEST'
export const OFFER_ALL_SUCCESS = 'OFFER_ALL_SUCCESS'
export const OFFER_ALL_FAIL = 'OFFER_ALL_FAIL'
export const OFFER_ALL_RESET = 'OFFER_ALL_RESET'

export const OFFER_REMOVE_REQUEST = 'OFFER_REMOVE_REQUEST'
export const OFFER_REMOVE_SUCCESS = 'OFFER_REMOVE_SUCCESS'
export const OFFER_REMOVE_FAIL = 'OFFER_REMOVE_FAIL'
export const OFFER_REMOVE_RESET = 'OFFER_REMOVE_RESET'

export const OFFER_GET_REQUEST = 'OFFER_GET_REQUEST'
export const OFFER_GET_SUCCESS = 'OFFER_GET_SUCCESS'
export const OFFER_GET_FAIL = 'OFFER_GET_FAIL'
export const OFFER_GET_RESET = 'OFFER_GET_RESET'

export const OFFER_ADD_STUDENT_REQUEST = 'OFFER_ADD_STUDENT_REQUEST'
export const OFFER_ADD_STUDENT_SUCCESS = 'OFFER_ADD_STUDENT_SUCCESS'
export const OFFER_ADD_STUDENT_FAIL = 'OFFER_ADD_STUDENT_FAIL'
export const OFFER_ADD_STUDENT_RESET = 'OFFER_ADD_STUDENT_RESET'

export const OFFER_ACCEPT_STUDENT_REQUEST = 'OFFER_ACCEPT_STUDENT_REQUEST'
export const OFFER_ACCEPT_STUDENT_SUCCESS = 'OFFER_ACCEPT_STUDENT_SUCCESS'
export const OFFER_ACCEPT_STUDENT_FAIL = 'OFFER_ACCEPT_STUDENT_FAIL'
export const OFFER_ACCEPT_STUDENT_RESET = 'OFFER_ACCEPT_STUDENT_RESET'

export const OFFER_ACCEPT_DELETE_STUDENT_REQUEST = 'OFFER_ACCEPT_DELETE_STUDENT_REQUEST'
export const OFFER_ACCEPT_DELETE_STUDENT_SUCCESS = 'OFFER_ACCEPT_DELETE_STUDENT_SUCCESS'
export const OFFER_ACCEPT_DELETE_STUDENT_FAIL = 'OFFER_ACCEPT_DELETE_STUDENT_FAIL'
export const OFFER_ACCEPT_DELETE_STUDENT_RESET = 'OFFER_ACCEPT_DELETE_STUDENT_RESET'