export const TRAINING_CREATE_REQUEST = 'TRAINING_CREATE_REQUEST'
export const TRAINING_CREATE_SUCCESS = 'TRAINING_CREATE_SUCCESS'
export const TRAINING_CREATE_FAIL = 'TRAINING_CREATE_FAIL'
export const TRAINING_CREATE_RESET = 'TRAINING_CREATE_RESET'

export const TRAINING_PUBLIC_REQUEST = 'TRAINING_PUBLIC_REQUEST'
export const TRAINING_PUBLIC_SUCCESS = 'TRAINING_PUBLIC_SUCCESS'
export const TRAINING_PUBLIC_FAIL = 'TRAINING_PUBLIC_FAIL'
export const TRAINING_PUBLIC_RESET = 'TRAINING_PUBLIC_RESET'

export const TRAINING_GET_ALL_REQUEST = 'TRAINING_GET_ALL_REQUEST'
export const TRAINING_GET_ALL_SUCCESS = 'TRAINING_GET_ALL_SUCCESS'
export const TRAINING_GET_ALL_FAIL = 'TRAINING_GET_ALL_FAIL'

export const TRAINING_ALL_REQUEST = 'TRAINING_ALL_REQUEST'
export const TRAINING_ALL_SUCCESS = 'TRAINING_ALL_SUCCESS'
export const TRAINING_ALL_FAIL = 'TRAINING_ALL_FAIL'
export const TRAINING_ALL_RESET = 'TRAINING_ALL_RESET'

export const TRAINING_DELETE_REQUEST = 'TRAINING_DELETE_REQUEST'
export const TRAINING_DELETE_SUCCESS = 'TRAINING_DELETE_SUCCESS'
export const TRAINING_DELETE_FAIL = 'TRAINING_DELETE_FAIL'
export const TRAINING_DELETE_RESET = 'TRAINING_DELETE_RESET'

export const TRAINING_GET_REQUEST = 'TRAINING_GET_REQUEST'
export const TRAINING_GET_SUCCESS = 'TRAINING_GET_SUCCESS'
export const TRAINING_GET_FAIL = 'TRAINING_GET_FAIL'
export const TRAINING_GET_RESET = 'TRAINING_GET_RESET'

export const TRAINING_ADD_STUDENT_REQUEST = 'TRAINING_ADD_STUDENT_REQUEST'
export const TRAINING_ADD_STUDENT_SUCCESS = 'TRAINING_ADD_STUDENT_SUCCESS'
export const TRAINING_ADD_STUDENT_FAIL = 'TRAINING_ADD_STUDENT_FAIL'
export const TRAINING_ADD_STUDENT_RESET = 'TRAINING_ADD_STUDENT_RESET'

export const TRAINING_ACCEPT_STUDENT_REQUEST = 'TRAINING_ACCEPT_STUDENT_REQUEST'
export const TRAINING_ACCEPT_STUDENT_SUCCESS = 'TRAINING_ACCEPT_STUDENT_SUCCESS'
export const TRAINING_ACCEPT_STUDENT_FAIL = 'TRAINING_ACCEPT_STUDENT_FAIL'
export const TRAINING_ACCEPT_STUDENT_RESET = 'TRAINING_ACCEPT_STUDENT_RESET'

export const TRAINING_ACCEPT_DELETE_STUDENT_REQUEST = 'TRAINING_ACCEPT_DELETE_STUDENT_REQUEST'
export const TRAINING_ACCEPT_DELETE_STUDENT_SUCCESS = 'TRAINING_ACCEPT_DELETE_STUDENT_SUCCESS'
export const TRAINING_ACCEPT_DELETE_STUDENT_FAIL = 'TRAINING_ACCEPT_DELETE_STUDENT_FAIL'
export const TRAINING_ACCEPT_DELETE_STUDENT_RESET = 'TRAINING_ACCEPT_DELETE_STUDENT_RESET'