export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_LOGIN_ERROR_RESET = 'USER_LOGIN_ERROR_RESET'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'
export const USER_REGISTER_RESET = 'USER_REGISTER_RESET'
export const USER_REGISTER_ERROR_RESET = 'USER_REGISTER_ERROR_RESET'

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST'
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL'
export const USER_PROFILE_RESET = 'USER_PROFILE_RESET'

export const USER_GET_REQUEST = 'USER_GET_REQUEST'
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS'
export const USER_GET_FAIL = 'USER_GET_FAIL'

export const USER_PROFILE_UPDATE_REQUEST = 'USER_PROFILE_UPDATE_REQUEST'
export const USER_PROFILE_UPDATE_SUCCESS = 'USER_PROFILE_UPDATE_SUCCESS'
export const USER_PROFILE_UPDATE_FAIL = 'USER_PROFILE_UPDATE_FAIL'
export const USER_PROFILE_UPDATE_RESET = 'USER_PROFILE_UPDATE_RESET'

export const USER_DELETE_FIELD_REQUEST = 'USER_DELETE_FIELD_REQUEST'
export const USER_DELETE_FIELD_SUCCESS = 'USER_DELETE_FIELD_SUCCESS'
export const USER_DELETE_FIELD_FAIL = 'USER_DELETE_FIELD_FAIL'
export const USER_DELETE_FIELD_RESET = 'USER_DELETE_FIELD_RESET'

export const USER_GET_ALL_USERS_REQUEST = 'USER_GET_ALL_USERS_REQUEST'
export const USER_GET_ALL_USERS_SUCCESS = 'USER_GET_ALL_USERS_SUCCESS'
export const USER_GET_ALL_USERS_FAIL = 'USER_GET_ALL_USERS_FAIL'

export const USER_NEW_EXPERIENCE_REQUEST = 'USER_NEW_EXPERIENCE_REQUEST'
export const USER_NEW_EXPERIENCE_SUCCESS = 'USER_NEW_EXPERIENCE_SUCCESS'
export const USER_NEW_EXPERIENCE_FAIL = 'USER_NEW_EXPERIENCE_FAIL'
export const USER_NEW_EXPERIENCE_RESET = 'USER_NEW_EXPERIENCE_RESET'

export const USER_NEW_SKILL_REQUEST = 'USER_NEW_SKILL_REQUEST'
export const USER_NEW_SKILL_SUCCESS = 'USER_NEW_SKILL_SUCCESS'
export const USER_NEW_SKILL_FAIL = 'USER_NEW_SKILL_FAIL'
export const USER_NEW_SKILL_RESET = 'USER_NEW_SKILL_RESET'

export const USER_DELETE_SKILL_REQUEST = 'USER_DELETE_SKILL_REQUEST'
export const USER_DELETE_SKILL_SUCCESS = 'USER_DELETE_SKILL_SUCCESS'
export const USER_DELETE_SKILL_FAIL = 'USER_DELETE_SKILL_FAIL'
export const USER_DELETE_SKILL_RESET = 'USER_DELETE_SKILL_RESET'

export const USER_REQUESTS_REQUEST = 'USER_REQUESTS_REQUEST'
export const USER_REQUESTS_SUCCESS = 'USER_REQUESTS_SUCCESS'
export const USER_REQUESTS_FAIL = 'USER_REQUESTS_FAIL'

export const USER_ACCEPTED_REQUESTS_REQUEST = 'USER_ACCEPTED_REQUESTS_REQUEST'
export const USER_ACCEPTED_REQUESTS_SUCCESS = 'USER_ACCEPTED_REQUESTS_SUCCESS'
export const USER_ACCEPTED_REQUESTS_FAIL = 'USER_ACCEPTED_REQUESTS_FAIL'

export const USER_FORGOT_PASSWORD_REQUEST = 'USER_FORGOT_PASSWORD_REQUEST'
export const USER_FORGOT_PASSWORD_SUCCESS = 'USER_FORGOT_PASSWORD_SUCCESS'
export const USER_FORGOT_PASSWORD_FAIL = 'USER_FORGOT_PASSWORD_FAIL'
export const USER_FORGOT_PASSWORD_RESET = 'USER_FORGOT_PASSWORD_RESET'

export const USER_RESET_PASSWORD_REQUEST = 'USER_RESET_PASSWORD_REQUEST'
export const USER_RESET_PASSWORD_SUCCESS = 'USER_RESET_PASSWORD_SUCCESS'
export const USER_RESET_PASSWORD_FAIL = 'USER_RESET_PASSWORD_FAIL'
export const USER_RESET_PASSWORD_RESET = 'USER_RESET_PASSWORD_RESET'

export const USER_ADD_BOOKMARK_REQUEST = 'USER_ADD_BOOKMARK_REQUEST'
export const USER_ADD_BOOKMARK_SUCCESS = 'USER_ADD_BOOKMARK_SUCCESS'
export const USER_ADD_BOOKMARK_FAIL = 'USER_ADD_BOOKMARK_FAIL'
export const USER_ADD_BOOKMARK_RESET = 'USER_ADD_BOOKMARK_RESET'

export const USER_GET_BOOKMARKS_REQUEST = 'USER_GET_BOOKMARKS_REQUEST'
export const USER_GET_BOOKMARKS_SUCCESS = 'USER_GET_BOOKMARKS_SUCCESS'
export const USER_GET_BOOKMARKS_FAIL = 'USER_GET_BOOKMARKS_FAIL'
export const USER_GET_BOOKMARKS_RESET = 'USER_GET_BOOKMARKS_RESET'

export const USER_DELETE_BOOKMARK_REQUEST = 'USER_DELETE_BOOKMARK_REQUEST'
export const USER_DELETE_BOOKMARK_SUCCESS = 'USER_DELETE_BOOKMARK_SUCCESS'
export const USER_DELETE_BOOKMARK_FAIL = 'USER_DELETE_BOOKMARK_FAIL'
export const USER_DELETE_BOOKMARK_RESET = 'USER_DELETE_BOOKMARK_RESET'

export const USER_MARK_REQUEST = 'USER_MARK_REQUEST'
export const USER_MARK_SUCCESS = 'USER_MARK_SUCCESS'
export const USER_MARK_FAIL = 'USER_MARK_FAIL'
export const USER_MARK_RESET = 'USER_MARK_RESET'

export const USER_MARK_ONE_REQUEST = 'USER_MARK_ONE_REQUEST'
export const USER_MARK_ONE_SUCCESS = 'USER_MARK_ONE_SUCCESS'
export const USER_MARK_ONE_FAIL = 'USER_MARK_ONE_FAIL'
export const USER_MARK_ONE_RESET = 'USER_MARK_ONE_RESET'